### ISSUE TITLE
Add tutorials(notebooks  + Colab links)

### ISSUE THREAD

**Issue by bcebere** [vanderschaarlab/temporai#44]
## Description
 - The library should have a tutorial for each major feature.
 - The tutorials should be notebooks, and should be also deployed on Colab, for easier use.

**Comment by DrShushen** [comment]
Tutorials and Colab links(https://github.com/vanderschaarlab/temporai/issues/44): first, some notebooks for all the relevant features. Then, after the PyPI deploy, some Colab links for ease of use/testing.
