### ISSUE TITLE
nn_regressor: Pydantic crash

### ISSUE THREAD

**Issue by bcebere** [vanderschaarlab/temporai#47]
## Description
Pydantic imposes a limit on the number of temporai objects that can be instantiated.

Example: In the test_nn_regressor.py,  the following snippet will crash
```python
 def test_hyperparam_sample():
     for repeat in range(10000):  # pylint: disable=unused-variable
         args = plugin._cls.sample_hyperparameters()  # pylint: disable=no-member, protected-access
         plugin(**args)
```
with the error
```
>   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for _InitArgsValidator
E   __root__
E     Model parameters could not be validated as defined by `EmptyParamsDefinition`, cause: 
E   ---------------
E   RecursionError:
E   maximum recursion depth exceeded
E   ---------------
E    (type=value_error)

pydantic/main.py:342: ValidationError

```
## Expected behaviour

Pydantic should not limit the functionality of the library.

**Comment by TZTsai** [comment]
I tried to run this snippet and it worked find. Is this issue resolved already?
![图片](https://user-images.githubusercontent.com/34415979/229930491-b9b15dd5-6f4c-457c-8d12-deaed5afb992.png)

**Comment by DrShushen** [comment]
This has been resolved, but thanks for looking into it.

**Comment by DrShushen** [comment]
Closing, resolved in https://github.com/vanderschaarlab/temporai/pull/50
