### ISSUE TITLE
why not contribute this to sktime?

### ISSUE THREAD

**Issue by fkiraly** [vanderschaarlab/temporai#60]
It would seem that this package is "cloning" a number of core aspects of sktime, including data format, base class design, etc.

It does add some novel aspects, but there aren't too many differences at the moment.
So, why develop this in complete detachment from the pydata ecosytem?

Long-term, it will be much harder to maintain if you insist on trying to build a parallel ecosystem targeted at medical doctors.

I understand the academic sensitivities of wanting to "own", but that's not really how open source works - the more you give and let go of, the more you get back, and the more successful you will be.

For instance, why not contribute this to sktime?

**Comment by fkiraly** [comment]
PS: the same argument ("owned" by me or anyone else) does not apply to sktime due to its participative governance mode (which is also undergoing a current update to include users). So, say, you contribute this in a reasonable form, and that makes you in-princinple eligible to "run" sktime (by various election and decision making mechanisms).

**Comment by DrShushen** [comment]
Thank you for your thoughtful and insightful feedback.
We will carefully consider your points as we continue to contribute to the broader open-source ecosystem.
Please note that the specific data format and class design we use are different from sktime and are not copied (though the popular sklearn style API is, of course, similar).
Once again, we appreciate your comments and recommendations.
