### ISSUE TITLE
[Enhancement] Achieve full docstring coverage

### ISSUE THREAD

**Issue by DrShushen** [vanderschaarlab/temporai#62]
There are still a few places where docstrings are needed. This enhancement would get docstring coverage to 100%.

**Comment by Rhobar9** [comment]
Can I take this issue?

**Comment by DrShushen** [comment]
Please feel free to do so, but I would recommend waiting until PR #64 is merged, as that has a couple of changes to docstrings

**Comment by Rhobar9** [comment]
Thank you for advice:) I will immediately start the task after PR.

**Comment by Rhobar9** [comment]
Thank you for whole bunch of advices:) I will start immediately. I only need 1-2 days for analyse all informations.  Obviously I will join the slack. Can I create my own fork?
Best regards,
